apiVersion: 1

datasources:
  - name: AMP
    type: prometheus
    access: proxy
    url: https://aps-workspaces.ap-northeast-2.amazonaws.com/workspaces/ws-c3787389-6902-4c4f-ac98-54699d1a7f11
    isDefault: true
    jsonData:
      sigV4Auth: true
      sigV4Region: ap-northeast-2